"use client"

import { useState, useEffect } from "react"
import { Header } from "@/components/header"

export default function PrivacyPage() {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 })

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      setMousePosition({
        x: e.clientX,
        y: e.clientY,
      })
    }

    window.addEventListener("mousemove", handleMouseMove)
    return () => window.removeEventListener("mousemove", handleMouseMove)
  }, [])
  return (
    <div className="relative min-h-screen bg-background flex flex-col">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(ellipse_at_center,rgba(0,0,0,0.2)_0%,rgba(0,0,0,0.6)_50%,rgba(0,0,0,0.9)_100%)]" />
      
      <div
        className="pointer-events-none fixed inset-0 bg-[linear-gradient(to_right,#3a3a4a_1px,transparent_1px),linear-gradient(to_bottom,#3a3a4a_1px,transparent_1px)] bg-[size:4rem_4rem]"
        style={{
          maskImage: "radial-gradient(ellipse at center, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.3) 50%, transparent 100%)",
          WebkitMaskImage:
            "radial-gradient(ellipse at center, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.3) 50%, transparent 100%)",
        }}
      />

      <div
        className="pointer-events-none fixed inset-0 bg-[linear-gradient(to_right,#4a5cb8_1px,transparent_1px),linear-gradient(to_bottom,#4a5cb8_1px,transparent_1px)] bg-[size:4rem_4rem] opacity-0 transition-opacity duration-300"
        style={{
          maskImage: `radial-gradient(circle 300px at ${mousePosition.x}px ${mousePosition.y}px, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 40%, transparent 70%)`,
          WebkitMaskImage: `radial-gradient(circle 300px at ${mousePosition.x}px ${mousePosition.y}px, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 40%, transparent 70%)`,
          opacity: 1,
        }}
      />

      <div className="relative z-10 flex min-h-screen flex-col">
        <Header />
        
        <main className="flex-1 container mx-auto px-4 py-24 md:py-32 max-w-4xl">
          <div className="prose prose-invert prose-lg max-w-none">
            <h1 className="text-4xl font-bold tracking-tight mb-8">Privacy Policy</h1>
            <p className="text-muted-foreground mb-8">Last updated: December 25, 2025</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">1. Introduction</h2>
              <p className="text-muted-foreground">
                NearNoi ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website nearnoi.me, use our dashboard at dashboard.nearnoi.me, or use our API services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">2. Information We Collect</h2>
              <p className="text-muted-foreground mb-4">
                We collect information that you provide directly to us when you use our Service:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li><strong>Wallet Information:</strong> Your NEAR Protocol wallet address and transaction history related to our Service.</li>
                <li><strong>Usage Data:</strong> Information about how you use our API, including timestamps, request counts, and error logs.</li>
                <li><strong>Content Data:</strong> The text, code, or other content you input into the Service ("Inputs") and the content generated by the Service ("Outputs").</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">3. Data Sharing with OpenAI and Model Providers</h2>
              <div className="p-6 border border-primary/20 bg-primary/5 rounded-lg mb-6">
                <h3 className="text-lg font-medium text-primary mb-2">Important Disclosure Regarding OpenAI</h3>
                <p className="text-muted-foreground">
                  By using NearNoi, you explicitly acknowledge and agree that your Inputs and Outputs are shared with OpenAI and other third-party model providers to facilitate the Service.
                </p>
                <p className="text-muted-foreground mt-4">
                  <strong>Agreement to OpenAI Policies:</strong> You must agree to and comply with all of OpenAI's policies, including their Terms of Use and Privacy Policy.
                </p>
                <p className="text-muted-foreground mt-4">
                  <strong>Training and Improvement:</strong> Inputs and outputs are shared with OpenAI from our organization to help develop and improve services, including for improving and training models. By using our Service, you consent to this sharing. Your data may be used by OpenAI to train and improve their models.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">4. Data Retention</h2>
              <p className="text-muted-foreground">
                We retain your personal information and Content Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="text-muted-foreground mt-2">
                Specific API logs and content history may be retained for a period of 30 days for debugging and abuse monitoring purposes, after which they are either deleted or anonymized, unless required otherwise by law or for the improvement of our services as described in Section 3.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">5. Security of Your Data</h2>
              <p className="text-muted-foreground">
                The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">6. Blockchain Data</h2>
              <p className="text-muted-foreground">
                Please be aware that transactions on the NEAR Protocol are public. Your wallet address and transaction details associated with payments to NearNoi will be publicly visible on the blockchain. We do not control and are not responsible for this public availability.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 text-foreground">7. Contact Us</h2>
              <p className="text-muted-foreground">
                If you have any questions about this Privacy Policy, please contact us at privacy@nearnoi.me.
              </p>
            </section>
          </div>
        </main>
      </div>
    </div>
  )
}
